version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 906733482679.dkr.ecr.ap-south-1.amazonaws.com/test-application)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - REPOSITORY_URI=906733482679.dkr.ecr.ap-south-1.amazonaws.com/test-application
      - echo "Using repository URI: $REPOSITORY_URI"
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "Using image tag: $IMAGE_TAG"
      - IMAGE_URI=$REPOSITORY_URI:$COMMIT_HASH
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $IMAGE_URI .
  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push $IMAGE_URI
      - echo Writing image URI to imagedefinitions.json...
      - printf '[{"name":"<container-name>","imageUri":"%s"}]' $IMAGE_URI > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
